#!/bin/bash

HOST=`hostname`
DATE=`date +%m-%d-%Y`
CRONDIR=/var/spool/cron/tabs

# Gather the information and make the report
echo "SERVER AND OS INFORMATION"
echo "uname -a"
uname -a 
echo "------------------------------------------------------"
echo "uptime"
uptime
echo "------------------------------------------------------"
echo "/boot/"
ls -lk /boot/
echo "------------------------------------------------------"
echo "/boot/grub/"
ls -lk /boot/grub/
echo "------------------------------------------------------"
echo "FILE SYSTEM INFORMATON"
echo "------------------------------------------------------"
echo "fdisk info"
fdisk -l | egrep '^Disk' |egrep -v 'dm-' 2> /dev/null 
echo "------------------------------------------------------"
echo "/etc/fstab"
cat /etc/fstab
echo "------------------------------------------------------"
echo "df -hP Output"
echo "------------------------------------------------------"
df -hP
echo "------------------------------------------------------"
echo "LVM INFORMATION"
echo "------------------------------------------------------"
echo "Physical Volumes"
pvs
echo "Volume Groups"
vgs
echo "Logical Volumes"
lvs
echo "======================================================"
echo "USER AND GROUP INFORMATION"
echo "------------------------------------------------------"
echo "/etc/passwd"
echo "------------------------------------------------------"
cat  /etc/passwd
echo "-------------------------------------------------------"
echo "/etc/shadow Ouptut"
echo "------------------------------------------------------"
cat /etc/shadow
echo "-------------------------------------------------------"
echo "/etc/group Output"
echo "------------------------------------------------------"
cat /etc/group
echo "======================================================"
echo "NETWORK INFORMATION"
echo "------------------------------------------------------"
echo "ifconfig Output"
echo "------------------------------------------------------"
ifconfig
echo "-------------------------------------------------------"
echo "Misc Network INFORMATION"
echo "------------------------------------------------------"
echo "IP info"
ip addr show
echo "Route info"
ip route
echo "ip neigh info"
ip neigh show
echo "======================================================"
echo "CRONTAB INFORMATION"
echo "-------------------------------------------------------"
echo "Crontabs"
echo "------------------------------------------------------"
for i in `ls $CRONDIR/`;do
        echo "$i crontab"
        cat $CRONDIR/$i
done
echo "------------------------------------------------------"
echo "Running Processes"
ps -ef
