#!/bin/bash

######################################
#This script is made by Chetan Sharma#
######################################

OUTPUT=$(ps -ef |grep -i splunk |grep -i pid |awk '{print $10}')

if [[ "$OUTPUT" = "splunkd" ]];
        then
                echo ""
                echo "Splunk is running."
                echo ""
        else
                echo ""
                echo "Splunk is NOT running...."
                echo ""
                read -p "Do you want to start Splunk now [ yes - no ]? " answer1
                if [[ "$answer1" = "yes" ]];
                        then
                                echo "" 
                                echo "Splunk will start now...."
                                sleep 3
                                /etc/init.d/splunk start
                fi 
                if [[ "$answer1" = "no" ]];
                        then 
                                echo ""
                                echo "Exiting now, nothing to do." 
                                echo ""
                                sleep 2
                fi 

fi
